### ISSUE TITLE
Element Instance contains meta-information about the workflow

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeeqs#11]
An element instance contains a list of meta-information from the workflow
- [ ]  message name of message event
- [x]  condition expression of sequence flows on an exclusive gateway
- [x]  job-type of service task
- [x]  error code of error event
- [x]  timer definition from timer event
- [x]  called process id of call activity

See also https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/master/src/main/java/io/zeebe/monitor/rest/ProcessesViewController.java#L245
